apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-jgjcrqgt
  janus-idp.io/tekton: go-jgjcrqgt
  backstage.io/kubernetes-id: go-jgjcrqgt
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-jgjcrqgt
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
